### ISSUE TITLE
Echo

### ISSUE THREAD

**Issue by Madji** [prsai/ibotg#2]
does not turn off the echo mode. when sending a message from irc to telegram. the bot repeat a message is sent. how to turn off? or reseat problem. in the config file mode echo off. and how to disable the message root set about user messages? please help to solve this problem. just alternative bot no and it is very useful for me

**Comment by Madji** [comment]
irc 
(10:58:35) unknown: [User_Name] Testing from telegram to irc
(10:59:11) biodamage: User_Name test answer from irc to telegram
(10:59:11) unknown: [User_Name#1] test answer from irc to telegram<  the bot repeat a message is sent.. this

**Comment by prsai** [comment]
I think this is because you didn't set tg_name with your name (shown in telegram) in the config file. Don't forget to replace the white spaces in the name (if any) with underscores (_).

Also I want to note that even with tg_echo=0, the message sent will be repeated by root (in IRC). This is the way telegram-cli works and it's useful to get feedback that your message has been delivered to telegram, but if you need I can create a new option to suppress totally the echo messages.

**Comment by Madji** [comment]
is it possible to make then not to come what happens action telegram? typing sending voice e.g or option to the config to disable it. you will not believe you are the only one who created such. else is doing just to chat. and email where I can send a donation

**Comment by prsai** [comment]
If I understand you only want the messages, not the status texts, a quick solution could be configure your IRC client to ignore the root user, all major IRC clients support that.

On the other hand I can add a new option in the config to disable the output of root user entirely, it's not difficult, I will have a look at this.

**Comment by Madji** [comment]
Yes, I think in the config to make the ability to disable a lot better. Thank you very much

**Comment by prsai** [comment]
I just pushed this to git: c1f049841bbe865c0a2a582cc53ffe559b27b024

Set tg_verbose=0 in config and root will be quiet.

**Comment by Madji** [comment]
Thanks!
